name: Release

on:
  release:
    types: [published]

jobs:
  publish-release-to-sonatype:
    name: Publish release artifact to Sonatype
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Deploy artifact
        env:           
          MAVEN_SECRING_GPG_BASE64: ${{ secrets.MAVEN_SECRING_GPG_BASE64 }}
          MAVEN_SECRING_PASSWORD: ${{ secrets.MAVEN_SECRING_PASSWORD }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./gradlew publishToSonatype closeSonatypeStagingRepository -PisRelease=true
        # Test staging deploy and then remove code above and uncomment code below
        # run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository